routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::middleware(['auth', 'auth.admin'])->group(function() {
    Route::get('/', 'UploadController@dashboard')->name('main');
    
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/schools', 'SchoolsController');
    Route::resource('/users', 'UsersController');

    Route::get('/dashboard', 'UploadController@dashboard')->name('dashboard');

    Route::get('/links/list', 'LinksController@list')->name('links.list');

    Route::get('/report', 'ReportsController@index')->name('report');
});

Route::middleware(['auth', 'auth.school'])->group(function() {
    Route::get('/', 'UploadController@upload')->name('scans.upload');

    Route::get('/upload', 'UploadController@upload')->name('scans.upload');
    Route::post('/upload', 'UploadController@store')->name('scans.store');
    Route::get('/uploadResult/{category}', 'UploadController@uploadResult')->name('scans.result');

    Route::get('/links/create', 'LinksController@create')->name('links.create');
    Route::post('/links/store', 'LinksController@store')->name('links.store');
    Route::get('/links/result/{category}', 'LinksController@result')->name('links.result');

    Route::get('/status', 'UploadController@status')->name('status');

    Route::get('/report/create', 'ReportsController@create')->name('repotrs.create');
    Route::post('/report/store', 'ReportsController@store')->name('reports.store');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'school_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function hasRole($role) {
        return $this->roles->contains(\App\Role::where('name', $role)->first());
    }

    public function isAdmin() {
        return $this->hasRole('admin');
    }

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    public function school()
    {
        return $this->belongsTo(\App\School::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use \App\School;
use \App\User;
use \App\Role;

class UsersController extends Controller
{
    public function index() 
    {
        $users = User::all();
        return view('users.index', compact(['users']));
    }

    public function create() 
    {
        $schools = School::all();
        $roles = Role::all();
        return view('users.create', compact(['schools', 'roles']));
    }

    public function store(Request $request) 
    {
        $user = User::create([
            'name' => $request->input('login'),
            'email' => $request->input('email'),
            'password' => Hash::make($request->input('password')),
            'school_id' => $request->input('school'),
        ]);

        $user->roles()->attach($request->input('roles'));

        return redirect(route('users.index'));
    }

    public function edit(User $user) 
    {
        $schools = School::all();
        $roles = Role::all();
        return view('users.edit', compact(['user', 'schools', 'roles']));
    }

    public function update(Request $request, User $user) 
    {
        $user->name = $request->input('login');
        $user->email = $request->input('email');
        $user->school_id = $request->input('school');

        if ($request->has('password') && $request->input('password') != '') {
            $user->password = Hash::make($request->input('password'));
        }

        $user->save();
        $user->roles()->sync($request->input('roles'));

        return redirect(route('users.index'));
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Создание Пользователя</h2>
            <form action="{{ route('users.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="login">Имя пользователя</label>
                    <input type="text" class="form-control" id="login" name="login">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email">
                </div>
                <div class="form-group">
                    <label for="password">Пароль</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <div class="form-group">
                    <label for="school">Выберите учреждение</label>
                    <select class="form-control" id="school" name="school">
                        @forelse($schools as $school)
                        <option value="{{ $school->id }}">{{ $school->name }}</option>
                        @empty
                        @endforelse
                    </select>
                </div>
                <h3>Роли</h3>
                @foreach($roles as $role)
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="role-{{ $role->id }}" name="roles[]" value="{{ $role->id }}" {{ $role->name == 'school' ? 'checked' : '' }}>
                    <label class="form-check-label" for="role-{{ $role->id }}">{{ $role->name }}</label>
                </div>   
                @endforeach
                <br>
                <br>
                <input type="submit" value="Создать Пользователя" class="btn btn-primary m-auto mt-5">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Редактирование Пользователя</h2>
            <form action="{{ route('users.update', $user) }}" method="post">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="login">Имя пользователя</label>
                    <input type="text" class="form-control" id="login" name="login" value="{{ $user->name }}">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" value="{{ $user->email }}">
                </div>
                <div class="form-group">
                    <label for="password">Пароль</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <div class="form-group">
                    <label for="school">Выберите учреждение</label>
                    <select class="form-control" id="school" name="school">
                        @forelse($schools as $school)
                        <option value="{{ $school->id }}" {{ $user->school_id == $school->id ? 'selected' : '' }}>{{ $school->name }}</option>
                        @empty
                        @endforelse
                    </select>
                </div>
                <h3>Роли</h3>
                @foreach($roles as $role)
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="role-{{ $role->id }}" name="roles[]" value="{{ $role->id }}" {{ $user->roles->contains($role) ? 'checked' : '' }}>
                    <label class="form-check-label" for="role-{{ $role->id }}">{{ $role->name }}</label>
                </div>   
                @endforeach
                <br>
                <br>
                <input type="submit" value="Сохранить изменения" class="btn btn-primary m-auto mt-5">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Пользователи</h2>
        <a href="{{ route('users.create') }}" class="btn btn-primary mt-5 mb-5 float-right">Добавть Пользователя</a>
        <table class="table table-striped">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Email</th>
                <th scope="col">Логин</th>
                <th scope="col">Школа</th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @forelse($users as $user)
                <tr>
                    <th scope="row">{{ $user->id }}</th>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->school->name ?? ''}}</td>
                    <td><a href="{{ route('users.edit', $user) }}">Редактировать</a></td>
                </tr>
                @empty
                    <td colspan=5>Пусто</td>
                @endforelse
            </tbody>
            </table>
        </div>
    </div>
</div>
@endsection