routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::middleware(['auth', 'auth.admin'])->group(function() {
    Route::get('/', 'UploadController@dashboard')->name('main');
    
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/schools', 'SchoolsController');
    Route::resource('/users', 'UsersController');

    Route::get('/dashboard', 'UploadController@dashboard')->name('dashboard');

    Route::get('/links/list', 'LinksController@list')->name('links.list');

    Route::get('/report', 'ReportsController@index')->name('report');
});

Route::middleware(['auth', 'auth.school'])->group(function() {
    Route::get('/', 'UploadController@upload')->name('scans.upload');

    Route::get('/upload', 'UploadController@upload')->name('scans.upload');
    Route::post('/upload', 'UploadController@store')->name('scans.store');
    Route::get('/uploadResult/{category}', 'UploadController@uploadResult')->name('scans.result');

    Route::get('/links/create', 'LinksController@create')->name('links.create');
    Route::post('/links/store', 'LinksController@store')->name('links.store');
    Route::get('/links/result/{category}', 'LinksController@result')->name('links.result');

    Route::get('/status', 'UploadController@status')->name('status');

    Route::get('/report/create', 'ReportsController@create')->name('repotrs.create');
    Route::post('/report/store', 'ReportsController@store')->name('reports.store');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Category extends Model
{
    protected $fillable = ['name', 'folder'];
    public $timestamps = false;

    public function getFileListForSchool($school)
    {
        $files = \File::files(Storage::disk('local')->getDriver()->getAdapter()->getPathPrefix() . 'pdfs/' . $this->folder . '/' . $school->folder . '/');
        return $files;
    }

    public function getCountFilesForSchool($school)
    {
        $countFiles =  count($this->getFileListForSchool($school));
        return $countFiles;
    }

    public function getSummaryCountFiles()
    {
        $schools = School::all();
        $countFiles = $schools->sum(function($school) {
            return $this->getCountFilesForSchool($school);
        });
        return $countFiles;
    }

    public function scopeActive($query)
    {
        return $query->where('active', 1);
    }

    public function reports()
    {
        return $this->hasMany('App\Report');
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\School;
use Illuminate\Support\Facades\Storage;

class CategoriesController extends Controller
{
    public function index() 
    {
        $categories = \App\Category::all();
        return view('categories.index', compact(['categories']));
    }

    public function create() 
    {
        return view('categories.create');
    }

    public function store(Request $request) 
    {
        $category = Category::create([
            'name' => $request->input('category'),
            'folder' => $request->input('folder'),
        ]);

        Storage::disk('local')->makeDirectory('pdfs/' . $category->folder);

        $schools = School::all();
        foreach ($schools as $school) {
            Storage::disk('local')->makeDirectory('pdfs/' . $category->folder . '/' . $school->folder);
        }

        return redirect(route('categories.index'));
    }

    public function edit(Category $category) 
    {
        return view('categories.edit', compact(['category']));
    }

    public function update(Request $request, Category $category) 
    {
        $category->name = $request->input('category');
        $category->active = $request->input('active') ?? 0;
        $category->update();

        return redirect(route('categories.index'));
    }

    public function destroy(Category $category)
    {
        $category->delete();
        return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Создание предмета</h2>
            <form action="{{ route('categories.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="category">Название предмета</label>
                    <input type="text" class="form-control" id="category" name="category">
                </div>
                <div class="form-group">
                    <label for="folder">Имя папки</label>
                    <input type="text" class="form-control" id="folder" name="folder">
                </div>
                <input type="submit" value="Создать предмет" class="btn btn-primary m-auto">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2>Редактирование предмета "{{ $category->name }}"</h2>
            <form action="{{ route('categories.update', $category) }}" method="post">
                @csrf
                @method('PUT')
                <div class="form-group mb-3">
                    <label for="category">Название предмета</label>
                    <input type="text" class="form-control" id="category" name="category" value="{{ $category->name }}">
                </div>
                <div class="form-check mb-3">
                    <input class="form-check-input" type="checkbox" value="1" name="active" id="defaultCheck1" {{ $category->active ? 'checked' : '' }}>
                    <label class="form-check-label" for="defaultCheck1">
                        Активность
                    </label>
                </div>
                <input type="submit" value="Сохранить изменения" class="btn btn-primary m-auto">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Предметы</h2>
        <a href="{{ route('categories.create') }}" class="btn btn-primary mt-5 mb-5 float-right">Добавть предмет</a>
        <table class="table table-striped">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Предмет</th>
                <th scope="col">Активен</th>
                <th scope="col"></th>
                {{--<th scope="col"></th>--}}
                </tr>
            </thead>
            <tbody>
                @forelse($categories as $category)
                <tr>
                    <th scope="row">{{ $category->id }}</th>
                    <td>{{ $category->name }}</td>
                    <td><span class="{{ $category->active ? 'text-success' : 'text-danger' }}">{{ $category->active ? 'Да' : 'Нет' }}</span></td>
                    <td><a href="{{ route('categories.edit', $category) }}">Редактировать</a></td>
                    {{--<td><a href="" onclick="event.preventDefault();
                                            document.getElementById('remove-category-{{ $category->id }}').submit();">Удалить</a>
                        <form action="{{ route('categories.destroy', $category) }}" method="post" class="d-none" id="remove-category-{{ $category->id }}">
                            @csrf
                            @method('DELETE')
                        </form>
                    </td>--}}
                </tr>
                @empty
                    <td colspan=4>Пусто</td>
                @endforelse
            </tbody>
            </table>
        </div>
    </div>
</div>
@endsection