routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::middleware(['auth', 'auth.admin'])->group(function() {
    Route::get('/', 'UploadController@dashboard')->name('main');
    
    Route::resource('/categories', 'CategoriesController');
    Route::resource('/schools', 'SchoolsController');
    Route::resource('/users', 'UsersController');

    Route::get('/dashboard', 'UploadController@dashboard')->name('dashboard');

    Route::get('/links/list', 'LinksController@list')->name('links.list');

    Route::get('/report', 'ReportsController@index')->name('report');
});

Route::middleware(['auth', 'auth.school'])->group(function() {
    Route::get('/', 'UploadController@upload')->name('scans.upload');

    Route::get('/upload', 'UploadController@upload')->name('scans.upload');
    Route::post('/upload', 'UploadController@store')->name('scans.store');
    Route::get('/uploadResult/{category}', 'UploadController@uploadResult')->name('scans.result');

    Route::get('/links/create', 'LinksController@create')->name('links.create');
    Route::post('/links/store', 'LinksController@store')->name('links.store');
    Route::get('/links/result/{category}', 'LinksController@result')->name('links.result');

    Route::get('/status', 'UploadController@status')->name('status');

    Route::get('/report/create', 'ReportsController@create')->name('repotrs.create');
    Route::post('/report/store', 'ReportsController@store')->name('reports.store');
});

app/School.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    protected $fillable = ['name', 'folder'];
    public $timestamps = false;

    public function reports()
    {
        return $this->hasMany('App\Report');
    }
}

app/Http/Controllers/SchoolsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\School;
use \App\Category;
use Illuminate\Support\Facades\Storage;

class SchoolsController extends Controller
{
    public function index() 
    {
        $schools = \App\School::all();
        return view('schools.index', compact(['schools']));
    }

    public function create() 
    {
        return view('schools.create');
    }

    public function store(Request $request) 
    {
        $school = School::create([
            'name' => $request->input('school'),
            'folder' => $request->input('folder'),
        ]);

        $categories = Category::all();
        foreach ($categories as $category) {
            Storage::disk('local')->makeDirectory('pdfs/' . $category->folder . '/' . $school->folder);
        }

        return redirect(route('schools.index'));
    }

    public function edit(School $school) 
    {
        return view('schools.edit', compact(['school']));
    }

    public function update(Request $request, School $school) 
    {
        $school->name = $request->input('school');
        $school->update();

        return redirect(route('schools.index'));
    }

    public function destroy(School $school)
    {
        $school->delete();
        return redirect(route('schools.index'));
    }
}

resources/views/schools/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Создание Школы</h2>
            <form action="{{ route('schools.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="school">Название школы</label>
                    <input type="text" class="form-control" id="school" name="school">
                </div>
                <div class="form-group">
                    <label for="folder">Имя папки</label>
                    <input type="text" class="form-control" id="folder" name="folder">
                </div>
                <input type="submit" value="Создать школу" class="btn btn-primary m-auto">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/schools/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2>Редактирование Школы</h2>
            <form action="{{ route('schools.update', $school) }}" method="post">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="school">Название школы</label>
                    <input type="text" class="form-control" id="school" name="school" value="{{ $school->name }}">
                </div>
                <input type="submit" value="Сохранить изменения" class="btn btn-primary m-auto">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/schools/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <h2>Школы</h2>
        <a href="{{ route('schools.create') }}" class="btn btn-primary mt-5 mb-5 float-right">Добавть Школу</a>
        <table class="table table-striped">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Школа</th>
                <th scope="col"></th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @forelse($schools as $school)
                <tr>
                    <th scope="row">{{ $school->id }}</th>
                    <td>{{ $school->name }}</td>
                    <td><a href="{{ route('schools.edit', $school) }}">Редактировать</a></td>
                    <td><a href="" onclick="event.preventDefault();
                                            document.getElementById('remove-school-{{ $school->id }}').submit();">Удалить</a>
                        <form action="{{ route('schools.destroy', $school) }}" method="post" class="d-none" id="remove-school-{{ $school->id }}">
                            @csrf
                            @method('DELETE')
                        </form>
                    </td>
                </tr>
                @empty
                    <td colspan=4>Пусто</td>
                @endforelse
            </tbody>
            </table>
        </div>
    </div>
</div>
@endsection